//is this rendering everything client-side? might need to change this
// 'use client'; WILL NEED THIS LATER TO SHOW ACTIVE PAGE
//imports start
import type { Metadata } from 'next';
import { Crimson_Pro } from 'next/font/google';
import Link from '../../node_modules/next/link';
import './globals.css';
// import { usePathname } from 'next/navigation';WILL NEED THIS LATER TO SHOW ACTIVE PAGE

//imports end
const crimsonPro = Crimson_Pro({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Dominik Croci | Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const pathname = usePathname(); WILL NEED THIS LATER TO SHOW ACTIVE PAGE
  return (
    <html lang="en" className={crimsonPro.className}>
      <body>
        <nav className="p-6">
          <ul className="flex justify-between text-3xl">
            <li>
              <Link href={'/'}> Dominik Croci</Link>
            </li>
            <div className="flex gap-6">
              <li>
                <Link href={'/blog'}> Blog</Link>
              </li>
              <li>
                <Link href={'/projects'}> Projects</Link>
              </li>
            </div>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
